import { CATEGORY_LABELS } from './findings.js';
import { formatBytes } from './utils.js';

export function reportToMarkdown(report, options = {}) {
  const includeEvidence = options.includeEvidence !== false;
  const lines = [
    `# ShareGlass report: ${report.file.name}`,
    '',
    `- **Risk:** ${report.summary.level.toUpperCase()} (${report.summary.score}/100)`,
    `- **Type:** ${report.type.label}`,
    `- **Size:** ${formatBytes(report.file.size)}`,
    `- **SHA-256:** \`${report.file.sha256}\``,
    `- **Generated:** ${report.generatedAt}`,
    `- **Processing:** Local; the file was not uploaded by ShareGlass`,
    '',
    '## Findings',
    ''
  ];
  if (!report.findings.length) lines.push('No findings.');
  for (const item of report.findings) {
    lines.push(`### ${item.severity.toUpperCase()} · ${item.title}`);
    lines.push('');
    lines.push(item.description);
    if (includeEvidence && item.evidence) lines.push('', `- Evidence: ${item.evidence}`);
    if (item.path) lines.push(`- Location: \`${item.path}\``);
    if (item.remediation) lines.push(`- Suggested action: ${item.remediation}`);
    lines.push('');
  }
  lines.push('---', `Generated by ShareGlass ${report.shareglassVersion}.`);
  return lines.join('\n');
}

export function reportToJson(report, pretty = true) {
  return JSON.stringify(report, null, pretty ? 2 : 0);
}

export function categorySummary(report) {
  return Object.entries(report.summary.categories)
    .map(([category, count]) => ({ category, label: CATEGORY_LABELS[category] || category, count }))
    .sort((a, b) => b.count - a.count || a.label.localeCompare(b.label));
}
